wandb_version: 1

fire_h:
  desc: null
  value: 0.5333333333333333
fire_l:
  desc: null
  value: 0.126
thr_h:
  desc: null
  value: 0.3857142857142858
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722392374.42091
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.11.5
      5: 0.16.2
      8:
      - 5
      13: linux-x86_64
